export { SkRoot, SkLine, SkBlock, SkPill, SkLegalHero } from './primitives'
export { HomePageSkeleton } from './home-page-skeleton'
export { AboutPageSkeleton } from './about-page-skeleton'
export { ExpertisesPageSkeleton } from './expertises-page-skeleton'
export { ExpertiseDetailPageSkeleton } from './expertise-detail-skeleton'
export { RealisationsPageSkeleton } from './realisations-page-skeleton'
export { ProjectDetailPageSkeleton } from './project-detail-skeleton'
export { ClientsPageSkeleton } from './clients-page-skeleton'
export { ContactPageSkeleton } from './contact-page-skeleton'
export { QuotePageSkeleton } from './quote-page-skeleton'
export { LegalPageSkeleton } from './legal-page-skeleton'
export { CmsPageSkeleton } from './cms-page-skeleton'
